### ISSUE TITLE
Load model

### ISSUE THREAD

**Issue by kibamin** [phueb/DLSRL#9]
How can i load the model ?

**Comment by phueb** [comment]
This code is research-code, so my focus is not on providing a 
ready-to-load model. Please train a model on the data that is in the 
repo, and save it to your preferred format. Training is straightforward: 
Just execute run.py -a interleaved c 300. This script calls the srl_task 
function, which trains a model with LSTM cell size=300 . Should not take 
more than a couple of hours on a good GPU. Specifying the interleaved 
architecture is required for best performance.
